import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, onAuthStateChanged, setPersistence, browserLocalPersistence, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';

const firebaseConfig={apiKey:'AIzaSyBzuctjdTAHT3kxdrIZz9aGe5mGLsiGwx4',authDomain:'m3ssenger-50a21.firebaseapp.com',projectId:'m3ssenger-50a21',storageBucket:'m3ssenger-50a21.appspot.com',messagingSenderId:'245814154474',appId:'1:245814154474:web:0d59fafb4b03baa296f393'};
const app=initializeApp(firebaseConfig); const auth=getAuth(app); setPersistence(auth,browserLocalPersistence);
let mode='signin';
const root=document.getElementById('app');
function renderAuth(message=''){root.innerHTML=`<main class="auth"><section class="card"><div class="logo">Me and You</div><div class="sub">Private messaging, made simple.</div><div class="tabs"><button class="${mode==='signin'?'active':''}" id="signinTab">Sign in</button><button class="${mode==='signup'?'active':''}" id="signupTab">Create account</button></div><form class="form" id="authForm"><input id="email" type="email" placeholder="Email address" autocomplete="email" required><input id="password" type="password" placeholder="Password" autocomplete="current-password" minlength="6" required><button class="primary" type="submit">${mode==='signin'?'Sign in':'Create account'}</button></form><div class="status" id="status">${message}</div></section></main>`;document.getElementById('signinTab').onclick=()=>{mode='signin';renderAuth()};document.getElementById('signupTab').onclick=()=>{mode='signup';renderAuth()};document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const s=document.getElementById('status');s.textContent='Please wait…';try{const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(mode==='signin')await signInWithEmailAndPassword(auth,email,password);else await createUserWithEmailAndPassword(auth,email,password)}catch(err){s.textContent=err.message.replace('Firebase: ','')}}}
function renderHome(user){root.innerHTML=`<main class="home"><header class="top">Me and You</header><div class="empty">Signed in as <strong>${user.email}</strong><br><br>Your chats will appear here.</div></main>`}
renderAuth();
onAuthStateChanged(auth,user=>user?renderHome(user):renderAuth());
