const FIREBASE_VERSION='10.12.2';
const firebaseConfig={apiKey:'AIzaSyBzuctjdTAHT3kxdrIZz9aGe5mGLsiGwx4',authDomain:'m3ssenger-50a21.firebaseapp.com',projectId:'m3ssenger-50a21',storageBucket:'m3ssenger-50a21.appspot.com',messagingSenderId:'245814154474',appId:'1:245814154474:web:0d59fafb4b03baa296f393'};
const root=document.getElementById('app');
const CACHE_KEY='meandyou_chats_v1';
let mode='signin',auth=null,db=null,currentUser=null,unsubscribeChats=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cacheRead=()=>{try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'[]')}catch{return[]}};
const cacheWrite=v=>{try{localStorage.setItem(CACHE_KEY,JSON.stringify(v))}catch{}};
function renderAuth(message=''){root.innerHTML=`<main class="auth"><section class="card"><div class="logo">Me and You</div><div class="sub">Private messaging, made simple.</div><div class="tabs"><button class="${mode==='signin'?'active':''}" id="signinTab">Sign in</button><button class="${mode==='signup'?'active':''}" id="signupTab">Create account</button></div><form class="form" id="authForm"><input id="email" type="email" placeholder="Email address" autocomplete="email" required><input id="password" type="password" placeholder="Password" autocomplete="current-password" minlength="6" required><button class="primary" type="submit">${mode==='signin'?'Sign in':'Create account'}</button></form><div class="status" id="status">${esc(message)}</div></section></main>`;document.getElementById('signinTab').onclick=()=>{mode='signin';renderAuth()};document.getElementById('signupTab').onclick=()=>{mode='signup';renderAuth()};document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const s=document.getElementById('status');s.textContent='Please wait…';try{const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(mode==='signin')await auth.signInWithEmailAndPassword(email,password);else await auth.createUserWithEmailAndPassword(email,password)}catch(err){s.textContent=err.message.replace('Firebase: ','')}}}
function formatTime(ts){if(!ts)return'';const d=ts.toDate?ts.toDate():new Date(ts);if(Number.isNaN(d.getTime()))return'';return d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}
function renderChats(chats=[],connection='Connecting…'){root.innerHTML=`<main class="home"><header class="top"><div><b>Me and You</b><small id="connection">${esc(connection)}</small></div><button id="logout" aria-label="Sign out">↪</button></header><section class="chatList" id="chatList">${chats.length?chats.map(c=>`<article class="chatRow"><div class="avatar">${esc((c.name||'?')[0].toUpperCase())}</div><div class="chatInfo"><div class="chatName">${esc(c.name||'Chat')}</div><div class="lastMessage">${esc(c.lastMessage||'No messages yet')}</div></div><time>${formatTime(c.updatedAt||c.lastMessageAt)}</time></article>`).join(''):`<div class="empty"><div class="emptyIcon">♡</div><h2>No chats yet</h2><p>Your conversations will appear here.</p></div>`}</section></main>`;document.getElementById('logout').onclick=()=>auth.signOut();}
function listenChats(){if(unsubscribeChats)unsubscribeChats();const cached=cacheRead();renderChats(cached,'Connecting…');try{const {collection,query,where,onSnapshot}=db;const q=query(collection(db,'chats'),where('members','array-contains',currentUser.uid));unsubscribeChats=onSnapshot(q,snap=>{const chats=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.updatedAt?.toMillis?.()||b.updatedAt?.seconds*1000||0)-(a.updatedAt?.toMillis?.()||a.updatedAt?.seconds*1000||0));cacheWrite(chats);renderChats(chats,'Connected');},err=>{console.error(err);document.getElementById('connection')?.replaceChildren(document.createTextNode('Offline'));});}catch(err){console.error(err);renderChats(cached,'Offline');}}
async function init(){renderAuth();try{const [appMod,authMod,firestoreMod]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);const app=appMod.initializeApp(firebaseConfig);auth=authMod.getAuth(app);db=firestoreMod.getFirestore(app);await authMod.setPersistence(auth,authMod.browserLocalPersistence);auth.signInWithEmailAndPassword=authMod.signInWithEmailAndPassword.bind(null,auth);auth.createUserWithEmailAndPassword=authMod.createUserWithEmailAndPassword.bind(null,auth);auth.signOut=authMod.signOut.bind(null,auth);authMod.onAuthStateChanged(auth,user=>{currentUser=user;if(user)listenChats();else{if(unsubscribeChats)unsubscribeChats();renderAuth();}});}catch(err){console.error(err);const s=document.getElementById('status');if(s)s.textContent='Firebase is unavailable. Please refresh and try again.';}}
init();