const FIREBASE_VERSION='10.12.2';
const firebaseConfig={apiKey:'AIzaSyBzuctjdTAHT3kxdrIZz9aGe5mGLsiGwx4',authDomain:'m3ssenger-50a21.firebaseapp.com',projectId:'m3ssenger-50a21',storageBucket:'m3ssenger-50a21.appspot.com',messagingSenderId:'245814154474',appId:'1:245814154474:web:0d59fafb4b03baa296f393'};
const root=document.getElementById('app');
const CHAT_CACHE='meandyou_chats_v2', MSG_PREFIX='meandyou_messages_';
let auth,db,mods,currentUser=null,mode='signin',unsubscribeChats=null,unsubscribeMessages=null,currentChat=null;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const cacheGet=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const cacheSet=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const stampMs=t=>t?.toMillis?.()||t?.seconds*1000||new Date(t||0).getTime()||0;
function dateLabel(t){const ms=stampMs(t);if(!ms)return'';const d=new Date(ms),n=new Date(),a=new Date(d.getFullYear(),d.getMonth(),d.getDate()),b=new Date(n.getFullYear(),n.getMonth(),n.getDate()),days=Math.round((b-a)/86400000);if(days===0)return'Today';if(days===1)return'Yesterday';if(days<7)return d.toLocaleDateString([], {weekday:'long'});return d.toLocaleDateString([], {day:'numeric',month:'long',year:d.getFullYear()===n.getFullYear()?undefined:'numeric'});}
function timeLabel(t){const ms=stampMs(t);return ms?new Date(ms).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):'';}
function authError(err){const code=err?.code||'';const map={'auth/invalid-credential':'Incorrect email or password.','auth/invalid-login-credentials':'Incorrect email or password.','auth/user-not-found':'No account exists with this email.','auth/wrong-password':'Incorrect email or password.','auth/email-already-in-use':'An account already exists with this email.','auth/weak-password':'Password must be at least 6 characters.','auth/invalid-email':'Enter a valid email address.','auth/too-many-requests':'Too many attempts. Please wait and try again.','auth/network-request-failed':'Network error. Check your connection and try again.','auth/operation-not-allowed':'Email/password sign-in is not enabled in Firebase.'};return map[code]||String(err?.message||'Sign-in failed.').replace('Firebase: ','')}
function renderAuth(message=''){root.innerHTML=`<main class="auth"><section class="card"><div class="logo">Me and You</div><div class="sub">Private messaging, made simple.</div><div class="tabs"><button class="${mode==='signin'?'active':''}" id="signinTab">Sign in</button><button class="${mode==='signup'?'active':''}" id="signupTab">Create account</button></div><form class="form" id="authForm"><input id="email" type="email" placeholder="Email address" autocomplete="email" required><input id="password" type="password" placeholder="Password" autocomplete="current-password" minlength="6" required><button class="primary" id="authSubmit" type="submit">${mode==='signin'?'Sign in':'Create account'}</button></form><div class="status" id="status">${esc(message)}</div></section></main>`;document.getElementById('signinTab').onclick=()=>{mode='signin';renderAuth()};document.getElementById('signupTab').onclick=()=>{mode='signup';renderAuth()};document.getElementById('authForm').onsubmit=async e=>{e.preventDefault();const s=document.getElementById('status'),btn=document.getElementById('authSubmit');const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!auth||!mods){s.textContent='Connecting to Firebase… Please try again in a moment.';return}btn.disabled=true;s.textContent=mode==='signin'?'Signing in…':'Creating account…';try{if(mode==='signin')await mods.signInWithEmailAndPassword(auth,email,password);else await mods.createUserWithEmailAndPassword(auth,email,password);}catch(err){console.error(err);btn.disabled=false;s.textContent=authError(err)}}}
function renderChats(chats=[],connection='Connecting…'){root.innerHTML=`<main class="home"><header class="top"><div><b>Me and You</b><small id="connection">${esc(connection)}</small></div><div class="topActions"><button id="newChat" aria-label="New chat">＋</button><button id="logout" aria-label="Sign out">↪</button></div></header><section class="chatList">${chats.length?chats.map(c=>`<article class="chatRow" data-chat="${esc(c.id)}"><div class="avatar">${esc((c.name||'?')[0].toUpperCase())}</div><div class="chatInfo"><div class="chatName">${esc(c.name||'Chat')}</div><div class="lastMessage">${esc(c.lastMessage||'No messages yet')}</div></div><time>${timeLabel(c.updatedAt||c.lastMessageAt)}</time></article>`).join(''):`<div class="empty"><div class="emptyIcon">♡</div><h2>No chats yet</h2><p>Start a conversation with another account.</p></div>`}</section></main>`;document.getElementById('logout').onclick=()=>mods.signOut(auth);document.getElementById('newChat').onclick=renderNewChat;document.querySelectorAll('[data-chat]').forEach(x=>x.onclick=()=>openChat(x.dataset.chat));}
function listenChats(){if(unsubscribeChats)unsubscribeChats();const cached=cacheGet(CHAT_CACHE);renderChats(cached,'Connecting…');try{const q=mods.query(mods.collection(db,'chats'),mods.where('members','array-contains',currentUser.uid));unsubscribeChats=mods.onSnapshot(q,snap=>{const chats=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>stampMs(b.updatedAt||b.lastMessageAt)-stampMs(a.updatedAt||a.lastMessageAt));cacheSet(CHAT_CACHE,chats);renderChats(chats,'Connected');},err=>{console.error(err);document.getElementById('connection')?.replaceChildren(document.createTextNode('Offline'));});}catch(err){console.error(err);renderChats(cached,'Offline');}}
function renderNewChat(){root.innerHTML=`<main class="home"><header class="chatTop"><button id="back">‹</button><div><b>New chat</b><small>Find someone by email</small></div></header><section class="newChatBox"><form id="findForm" class="form"><input id="findEmail" type="email" placeholder="Email address" autocomplete="off" required><button class="primary">Find account</button></form><div id="findResult" class="status"></div></section></main>`;document.getElementById('back').onclick=()=>renderChats(cacheGet(CHAT_CACHE),'Connected');document.getElementById('findForm').onsubmit=findUser;}
async function findUser(e){e.preventDefault();const box=document.getElementById('findResult'),email=document.getElementById('findEmail').value.trim().toLowerCase();box.textContent='Searching…';try{let snap=await mods.getDocs(mods.query(mods.collection(db,'users'),mods.where('emailLower','==',email),mods.limit(1)));if(snap.empty)snap=await mods.getDocs(mods.query(mods.collection(db,'users'),mods.where('email','==',email),mods.limit(1)));if(snap.empty){const all=await mods.getDocs(mods.collection(db,'users'));const match=all.docs.find(d=>String(d.data().email||'').trim().toLowerCase()===email);if(match)snap={empty:false,docs:[match]};}if(snap.empty){box.textContent='No account found for that email.';return}const u={id:snap.docs[0].id,...snap.docs[0].data()};if(u.id===currentUser.uid){box.textContent='That is your own account.';return}box.innerHTML=`<button class="resultUser" id="startChat"><span class="avatar">${esc((u.displayName||u.email||'?')[0].toUpperCase())}</span><span><b>${esc(u.displayName||u.email)}</b><small>${esc(u.email)}</small></span></button>`;document.getElementById('startChat').onclick=()=>createChat(u);}catch(err){console.error(err);box.textContent=err?.code==='permission-denied'?'Firestore search is blocked by your Firebase rules.':'Could not search right now.';}}
async function createChat(u){const ids=[currentUser.uid,u.id].sort(),id=ids.join('_');try{const ref=mods.doc(db,'chats',id),snap=await mods.getDoc(ref);if(!snap.exists())await mods.setDoc(ref,{type:'direct',members:ids,names:{[currentUser.uid]:currentUser.email,[u.id]:u.displayName||u.email},lastMessage:'',createdAt:mods.serverTimestamp(),updatedAt:mods.serverTimestamp()});openChat(id);}catch(err){document.getElementById('findResult').textContent='Could not create chat.';console.error(err)}}
function otherName(chat){return chat?.names?.[Object.keys(chat.names||{}).find(id=>id!==currentUser.uid)]||'Chat';}
async function openChat(chatId){if(unsubscribeMessages)unsubscribeMessages();try{const ref=mods.doc(db,'chats',chatId),snap=await mods.getDoc(ref);if(!snap.exists())return;currentChat={id:chatId,...snap.data()};const cached=cacheGet(MSG_PREFIX+chatId);renderConversation(cached,'Connecting…');const q=mods.query(mods.collection(db,'chats',chatId,'messages'),mods.orderBy('createdAt','asc'));unsubscribeMessages=mods.onSnapshot(q,s=>{const msgs=s.docs.map(d=>({id:d.id,...d.data()}));cacheSet(MSG_PREFIX+chatId,msgs);renderConversation(msgs,'Connected');},err=>{console.error(err);document.getElementById('chatConnection')?.replaceChildren(document.createTextNode('Offline'));});}catch(err){console.error(err);renderChats(cacheGet(CHAT_CACHE),'Offline');}}
function renderConversation(messages=[],connection='Connecting…'){const name=otherName(currentChat);let lastDay='';const body=messages.map(m=>{const day=dateLabel(m.createdAt);const sep=day!==lastDay?(lastDay=day?`<div class="dateSep"><span>${esc(day)}</span></div>`:''):'';return `${sep}<div class="message ${m.senderId===currentUser.uid?'mine':'theirs'}"><div>${esc(m.text)}</div><time>${timeLabel(m.createdAt)}</time></div>`}).join('');root.innerHTML=`<main class="conversation"><header class="chatTop"><button id="backChats">‹</button><div class="chatTitle"><b>${esc(name)}</b><small id="chatConnection">${esc(connection)}</small></div></header><section class="messages" id="messages">${body||'<div class="empty">No messages yet.<br>Say hello 👋</div>'}</section><form class="composer" id="composer"><input id="messageInput" placeholder="Message" autocomplete="off"><button id="sendBtn" type="submit" aria-label="Send">➤</button></form></main>`;document.getElementById('backChats').onclick=()=>{if(unsubscribeMessages)unsubscribeMessages();renderChats(cacheGet(CHAT_CACHE),'Connected')};document.getElementById('composer').onsubmit=sendMessage;const list=document.getElementById('messages');list.scrollTop=list.scrollHeight;document.getElementById('messageInput').focus();}
async function sendMessage(e){e.preventDefault();const input=document.getElementById('messageInput'),text=input.value.trim();if(!text||!currentChat)return;input.value='';const now=mods.serverTimestamp();try{await mods.addDoc(mods.collection(db,'chats',currentChat.id,'messages'),{senderId:currentUser.uid,text,type:'text',createdAt:now});await mods.updateDoc(mods.doc(db,'chats',currentChat.id),{lastMessage:text,updatedAt:now,lastSenderId:currentUser.uid});}catch(err){console.error(err);input.value=text;}}
async function init(){renderAuth();try{const [appMod,authMod,firestoreMod]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${FIREBASE_VERSION}/firebase-firestore.js`)]);mods={...authMod,...firestoreMod};const app=appMod.initializeApp(firebaseConfig);auth=authMod.getAuth(app);db=firestoreMod.getFirestore(app);await authMod.setPersistence(auth,authMod.browserLocalPersistence);authMod.onAuthStateChanged(auth,user=>{currentUser=user;if(user){firestoreMod.setDoc(firestoreMod.doc(db,'users',user.uid),{email:user.email,emailLower:user.email.toLowerCase(),displayName:user.displayName||user.email.split('@')[0],updatedAt:firestoreMod.serverTimestamp()},{merge:true}).catch(err=>console.warn('Profile sync skipped:',err));listenChats();}else{if(unsubscribeChats)unsubscribeChats();if(unsubscribeMessages)unsubscribeMessages();renderAuth();}});}catch(err){console.error(err);const s=document.getElementById('status');if(s)s.textContent='Firebase is unavailable. Please refresh and try again.';}}
init();